#!/usr/bin/env bash

IMAGE_EXT="jpg jpeg gif bmp tif png raw awr psd xcf webp"
report_file="informe.html"
report_file_orig="informe"
begin_html="cabecera.html"
css_file="styles.css"
function print_begin_header_html(){
	report_file=$1
	echo "$repor_file"
	echo "print header $report_file"
	echo "<!DOCTYPE html>" >> $report_file
	echo "<html>" >> $report_file 
	echo "<title>Análisis forense</title>" >> $report_file
	echo "<head>" >> $report_file
		echo "<link rel=\"stylesheet\" href=\"$css_file\">" >> $report_file
	echo "</head>" >> $report_file
	echo "<body>" >> $report_file
	echo "<h1>Evidencias</h1>" >> $report_file
}

if [ "-s" == "$1" ]; then
	if [ "indagador_files.d/" == "$(basename $2)/" ]; then
		selected_files="${2}selected_files"
		dir_img_evidences="${2}img_evidences"
	else
		echo "Correct usage: generador_informe_por_fichero -s <ruta a indagador_files.d>/"
		exit
	fi
fi

mkdir -p "$dir_img_evidences"

if [ ! -f "$report_file" ]; then
	#cat $begin_html > $report_file
	print_begin_header_html $report_file
else
	count=0
	while [ -f "$report_file" ]; do
		count=$((count + 1))
		report_file="${report_file_orig}_${count}.html"
	done
	print_begin_header_html $report_file
fi


while IFS= read -r file_abs_path
do
	file=$(basename "$file_abs_path")
	file_extension=${file#*.}
	file_extension_lower_case=$(echo $file_extension | awk '{print tolower($0)}')

	echo "<h2>Evidencia: $file</h2>" >> $report_file
	for img_file_type in $IMAGE_EXT; do
		if [ $img_file_type == $file_extension_lower_case ]; then
			if [ ! -f "$dir_img_evidences/$file" ]; then
				cp "$file_abs_path" $dir_img_evidences
			fi
			echo "<div> <img src=\"$dir_img_evidences/$file\"></img> </div>" >> $report_file
			break
		fi
	done

	echo "<table>" >> $report_file
	while IFS= read -r line
	do
		echo "<tr>" >> $report_file
		echo "   <td>" >> $report_file
			var_name=$(echo $line | cut -f1 -d":")
			echo "   $var_name" >> $report_file
		echo "   </td>" >> $report_file
		echo "   <td>" >> $report_file
		var_data=$(echo $line | cut -f2 -d":")
			echo "   $var_data" >> $report_file
		echo "   </td>" >> $report_file
		echo "</tr>" >> $report_file
	done < <(exiftool "$file_abs_path" | tr -d " ")
	
	echo "<tr>" >> $report_file
		echo "<td>Hash sha256</td>" >> $report_file
		echo "<td>$(sha256sum "$file_abs_path" | cut -f1 -d' ')</td>" >> $report_file
	echo "</tr>" >> $report_file

	echo "</table>" >> $report_file

done < <(cat "$selected_files")

echo "</body>" >> $report_file
echo "</html>" >> $report_file
